name: open-science-rockies-2022-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - hvplot
  - datashader
  - bokeh
  - fiona
  - pip
  - pip:
    - -r doc-requirements.txt
